name: Unit tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
      - name: Install neurobooth-terra
        shell: bash -el {0}
        run: |
          python setup.py --verbose install
      - name: Test with pytest
        shell: bash -el {0}
        run: |
          python -m py.test . --cov=neurobooth_terra neurobooth_terra/tests/ --cov-report=xml
